/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idcardgeneratingsystem;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ccs
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private ImageIcon format=null;
    String fname=null;
    int s=0;
    byte[] pimage=null;
    int lvalue = 1000;
    
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelid = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblcountry = new javax.swing.JLabel();
        lblimage = new javax.swing.JLabel();
        lblnic = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblcountry2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        rSLabelImage3 = new rojerusan.RSLabelImage();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lblbday = new javax.swing.JLabel();
        lbladress = new javax.swing.JLabel();
        lblbcountry = new javax.swing.JLabel();
        lblinfor = new javax.swing.JLabel();
        rSLabelImage1 = new rojerusan.RSLabelImage();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bdate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadress = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtcountry = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        cmbgender = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtinfo = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(102, 0, 0));
        jPanel6.setDoubleBuffered(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcountry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblcountry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcountry.setText("Cuntry Here");
        jPanel10.add(lblcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, 40));

        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/idcardgeneratingsystem/good.jpg"))); // NOI18N
        jPanel10.add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 130, 130));

        lblnic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnic.setText("NIC Number Here");
        jPanel10.add(lblnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 94, 203, -1));

        jLabel12.setText("Date");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 277, 85, -1));

        lbldate.setText("Date Here");
        jPanel10.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 257, 85, -1));

        jLabel14.setText("Signature");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 277, 100, -1));

        jLabel15.setText(".........................");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 257, -1, -1));

        lblcountry2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblcountry2.setText("Cuntry Here");
        jPanel10.add(lblcountry2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 70, 20));

        jLabel23.setText("Goverment");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 70, 20));

        jLabel24.setText("This id issue by ");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 100, 20));

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Emblem_of_Sri_Lanka.svg.png"))); // NOI18N
        jPanel10.add(rSLabelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 270, 430));

        panelid.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 290, 450));

        jPanel7.setBackground(new java.awt.Color(102, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Name");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Gender");
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Birthday");
        jPanel12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Address");
        jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Country");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Info");
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 246, -1, -1));

        lblname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblname.setText("Name here");
        jPanel12.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 29, 160, -1));

        lblgender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblgender.setText("Gender here");
        jPanel12.add(lblgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 73, 130, -1));

        lblbday.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblbday.setText("Birthdat here");
        jPanel12.add(lblbday, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 115, 160, -1));

        lbladress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbladress.setText("Address here");
        jPanel12.add(lbladress, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 161, 160, -1));

        lblbcountry.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblbcountry.setText("Country here");
        jPanel12.add(lblbcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 203, 160, -1));

        lblinfor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblinfor.setText("Info here");
        jPanel12.add(lblinfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 246, 160, -1));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Emblem_of_Sri_Lanka.svg.png"))); // NOI18N
        jPanel12.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 100, 120));

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 240, 430));

        panelid.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 260, 450));

        jPanel3.add(panelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 590, 470));

        jLabel10.setFont(new java.awt.Font("Sitka Heading", 3, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NIC Generating System");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Name");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel4.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 250, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Birthday");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        bdate.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(bdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 250, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Address");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 183, -1, -1));

        txtadress.setColumns(20);
        txtadress.setRows(5);
        jScrollPane1.setViewportView(txtadress);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 250, 55));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cuntry");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));
        jPanel4.add(txtcountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 250, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Issue Date");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        idate.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(idate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 250, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Gender");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        cmbgender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gender", "Male", "Female" }));
        jPanel4.add(cmbgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Info");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 283, -1, -1));

        txtinfo.setColumns(20);
        txtinfo.setRows(5);
        jScrollPane2.setViewportView(txtinfo);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 250, 64));

        jButton1.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jButton1.setText("Upload Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 358, 330, 39));

        jButton2.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jButton2.setText("Genarate ID");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 116, 43));

        jButton3.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 128, 43));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 360, 470));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFileChooser fchoser=new JFileChooser();
        fchoser.showOpenDialog(null);
        File f=fchoser.getSelectedFile();
        fname=f.getAbsolutePath();
        ImageIcon micon=new ImageIcon(fname);        
        try {
            File image=new File(fname);
            FileInputStream fis=new FileInputStream(image);
            ByteArrayOutputStream baos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int readnum; (readnum=fis.read(buf)) !=-1;)
            {            
                baos.write(buf,0,readnum);                 
            }
            pimage=baos.toByteArray();
            lblimage.setIcon(resizeImage(fname, buf));
        } catch (Exception e) {
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String cou=txtcountry.getText();
        String date=((JTextField)idate.getDateEditor().getUiComponent()).getText();
        String birthday=((JTextField)bdate.getDateEditor().getUiComponent()).getText();
        String name= txtname.getText();
        String adress= txtadress.getText();
        String gender = cmbgender.getSelectedItem().toString();
        String info = txtinfo.getText();
        
        
        
        lblcountry.setText(cou);
        lblcountry2.setText(cou);
        lbldate.setText(date);
        lblbcountry.setText(cou);
        lblname.setText(name);
        lblbday.setText(birthday);
        lbladress.setText(adress);
        lblgender.setText(gender);
        lblinfor.setText(info);
        
        //id number generate
        String year= birthday.substring(2, 4);
       // JOptionPane.showMessageDialog(rootPane, year);
        int genvalue=0;
        if(gender.equals("Male"))
        {
            genvalue=100;
        }
        else{
            genvalue=500;
        }
        
        lvalue++;
        
        String gen = String.valueOf(genvalue);
        String las = String.valueOf(lvalue);
        String nic= year+gen+las+"V";
        
        lblnic.setText(nic);
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try {
            Toolkit tkp = panelid.getToolkit();
    PrintJob pjp = tkp.getPrintJob(this, null, null);
    Graphics g = pjp.getGraphics();
    panelid.print(g);
    g.dispose();
    pjp.end();
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

     public ImageIcon resizeImage(String imagePath, byte[] pic){
          
        ImageIcon myImage=null;
        if(imagePath !=null)
        {
        myImage=new ImageIcon(imagePath);
        
        }else{
         myImage=new ImageIcon(pic);
        }
                
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(lblimage.getHeight(), lblimage.getWidth(),  Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser bdate;
    private javax.swing.JComboBox cmbgender;
    private com.toedter.calendar.JDateChooser idate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbladress;
    private javax.swing.JLabel lblbcountry;
    private javax.swing.JLabel lblbday;
    private javax.swing.JLabel lblcountry;
    private javax.swing.JLabel lblcountry2;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lblinfor;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblnic;
    private javax.swing.JPanel panelid;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage3;
    private javax.swing.JTextArea txtadress;
    private javax.swing.JTextField txtcountry;
    private javax.swing.JTextArea txtinfo;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
